swagger: '2.0'
info:
  version: '1.0.0'
  title: CARMIN a Common web API for Remote pipeline INvocation
  description: FLI/IAM REST API for exchanging data and remote calling pipelines.

  #termsOfService: http://helloreverb.com/terms/
  #contact:
    #name: Swagger API team
    #email: foo@example.com
    #url: http://swagger.io
  #license:
    #name: MIT
    #url: http://opensource.org/licenses/MIT
#host: petstore.swagger.io
#basePath: /api
security: 
  - {basicAuth:[]}
  - {apiKey:[]}
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  basicAuth:
    type: basic
    description: If supported by the platform, it is possible to use HTTP
      Basic Authentication but one must call `/login_basic_http` before 
      calling any API service.
  apiKey:
      # TODO: Should we replace cookie authentication (not supported by Swagger)
      # by apiKey authentication ?
      type: apiKey
      name: api_key
      in: header
      description: If HTTP Basic authentication is not supported, calling
        `/login` allows for password checking and cookie based authentication.

paths:
  /login:
    get:
      description: |
        Check username and password and allow access to the API in case of 
        success by setting a cookie that must be used in any subsequent API
        calls.
      operationId: authenticateSession
      parameters:
        - name: username
          in: query
          description: Name of the user account.
          required: true
          type: string
          format: utf8
        - name: password
          in: query
          description: Password to verify.
          required: true
          type: string
          format: password
      responses:
        '200':
          description: Returns `success` if login is successful or `failure`
            if login and/or password is incorrect.
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorCodesAndMessage'
  /platform:
    get:
      description: Returns information about the platform
      operationId: getPlatformProperties
      produces:
        - application/json
      responses:
        '200':
          description: successful response
          schema:
            $ref: '#/definitions/platformProperties'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorCodesAndMessage'
  /studies:
    get:
      description: List all the allowed studies in terms of user right
      operationId: getStudies
      produces:
        - application/json
      responses:
        '200':
          description: successful response
          schema:
            $ref: '#/definitions/studies'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorCodesAndMessage'
    post:
      description: Create a new study. The user gets {study}_manager role.
        Returns all the information of {study} including platform-created `identifier`.
      operationId: postStudy
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          description: study to add in the database
          required: true
          schema:
            $ref: '#/definitions/newStudy'
      responses:
        '200':
          description: successfully create a new study
          schema:
            $ref: '#/definitions/study'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorCodesAndMessage'
  /studies/{study_name}:
    get:
      description: get study information by study name
      operationId: getStudy
      produces:
        - application/json
      parameters:
        - name: study_name
          in: path
          description: study name
          required: true
          type: string
      responses:
        '200':
          description: successful response
          schema:
            $ref: '#/definitions/study'
    put:
      description: modify some properties of a study
      operationId: putStudy
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          description: modify a value in the study by keyValuePair,
            i.e. description, contactEmail, base_path.
            The study name and the identifier cannot be changed.
          required: true
          schema:
            $ref: '#/definitions/keyValuePair'
        - name: study_name
          in: path
          description: study name
          required: true
          type: string
      responses:
        '200':
          description: successfully modify a study.
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorCodesAndMessage'
    delete:
      description: remove a study
      operationId: deleteStudy
      parameters:
        - name: study_name
          in: path
          description: study name
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: successful response
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorCodesAndMessage'
  /executions:
    get:
      description: |
        list all execution Ids in the platform which are ordered in decreasing submission time.
      operationId: getExecutions
      produces:
        - application/json
      responses:
        '200':
          description: successful response
          schema:
            $ref: '#/definitions/executionIds'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorCodesAndMessage'
  /studies/{study}/executions:
    get:
      description: list all execution Ids in the study called {study}
      operationId: getStudyExecutions
      parameters:
        - name: study
          in: path
          description: study name
          required: true
          type: string
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: successful response
          schema:
            $ref: '#/definitions/executionIds'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorCodesAndMessage'
    post:
      description: |
        initialize a new execution. All necessary data must have already been
        transferred to the platform. The execution may not start immediately 
        (according to a parameter). The user gets the role {execution}_owner.
      operationId: postStudyExecutions
      parameters:
        - name: study
          in: path
          description: study name
          required: true
          type: string
        - name: body
          in: body
          description: |
            An array of key value pairs. The definition is defined as below
          required: true
          schema:
            # it is defined by the pipeline definition.
            # The name denotes the name of parameter in pipeline
            # and the value denotes the value of parameter.
            $ref: '#/definitions/newExecution'
      produces:
        - application/json
      responses:
        '200':
          description: successful response
          schema:
            $ref: '#/definitions/executionId'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorCodesAndMessage'
  /studies/{study}/executions/{execution}:
    get:
      description: get information about an execution
      operationId: getStudyExecutionsExecution
      parameters:
        - name: study
          in: path
          description: study name
          required: true
          type: string
        - name: execution
          in: path
          description: execution id
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: successful response
          schema:
            $ref: '#/definitions/execution'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorCodesAndMessage'
    put:
      description: |
        Modify some parameters (i.e. name and timeout).
      operationId: putStudyExecutionsExecution
      consumes:
        - application/json
      parameters:
        - name: study
          in: path
          description: study name
          required: true
          type: string
        - name: execution
          in: path
          description: execution id
          required: true
          type: string
        - name: body
          in: body
          description: |
            For example, you can modify name 
            as key= "name" and value="execution name"
          required: false
          schema:
            $ref: '#/definitions/keyValuePair'
      responses:
        '200':
          description: successful response
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorCodesAndMessage'
    delete:
      description: |
        Delete an execution. This will kill the underlying processes (if possible)
        and free all resources associated with this execution.
      operationId: deleteStudyExecutionsExecution
      parameters:
        - name: study
          in: path
          description: study name
          required: true
          type: string
        - name: execution
          in: path
          description: execution id
          required: true
          type: string
      responses:
        '200':
          description: successful response
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorCodesAndMessage'
  /studies/{study}/executions/{execution}/play:
    get:
      description: play an execution
      operationId: getStudyExecutionsExecutionPlay
      parameters:
        - name: study
          in: path
          description: study name
          required: true
          type: string
        - name: execution
          in: path
          description: execution id
          required: true
          type: string
      responses:
        '200':
          description: successful response
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorCodesAndMessage'
  /studies/{study}/executions/{execution}/kill:
    get:
      description: kill an execution
      operationId: getStudyExecutionsExecutionKill
      parameters:
        - name: study
          in: path
          description: study name
          required: true
          type: string
        - name: execution
          in: path
          description: execution id
          required: true
          type: string
      responses:
        '200':
          description: successful response
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorCodesAndMessage'
  /studies/{study}/executions/{execution}/stdout:
    get:
      description: get stdout of an execution
      operationId: getStudyExecutionsExecutionStdout
      parameters:
        - name: study
          in: path
          description: study name
          required: true
          type: string
        - name: execution
          in: path
          description: execution id
          required: true
          type: string
      responses:
        '200':
          description: successful response
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorCodesAndMessage'
  /studies/{study}/executions/{execution}/stderr:
    get:
      description: get stderr of an execution
      operationId: getStudyExecutionsExecutionStderr
      parameters:
        - name: study
          in: path
          description: study name
          required: true
          type: string
        - name: execution
          in: path
          description: execution id
          required: true
          type: string
      responses:
        '200':
          description: successful response
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorCodesAndMessage'
  /pipelines:
    get:
      description: |
        All the pipelines that the user can execute must be returned.
        It is up to the platform to return pipelines that the user cannot execute.
        When studyIdentifier is present, all the pipelines that the user can execute
        in the study must be returned. In this case, execution rights denote the rights
        to execute the pipeline in the study.
      operationId: listPipelines
      produces:
        - application/json
      responses:
        '200':
          description: successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Pipeline'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorCodesAndMessage'
definitions:
  studies:
    type: array
    items:
      $ref: '#/definitions/study'
  newStudy:
    type: object
    required:
      - name
      - description
      - contactEmail
      - base_path
    properties:
      name:
        type: string
        description: study name
      description:
        type: string
        description: information about the study
      contactEmail:
        type: string
        description: email of someone that knows about this study in the platform
      base_path:
        type: string
        description: all files starting with base_path will be declared as belonging to the study
  study:
    type: object
    required:
      - name
      - identifier
      - description
      - contactEmail
      - base_path
    properties:
      name:
        type: string
        description: study name
      identifier:
        type: string
        description: study unique identifier
      description:
        type: string
        description: information about the study
      contactEmail:
        type: string
        description: email of someone that knows about this study in the platform
      base_path:
        type: string
        description: all files starting with base_path will be declared as belonging to the study
  platformProperties:
    type: object
    required:
      - platformName
      - supportedTransferProtocols
      - supportedModules
      - defaultLimitListExecutions
      - unsupportedMethods
      - supportedAPIVersion
    properties:
      platformName:
        type: string
        description: Name of the platform.
      APIErrorCodesAndMessages:
        type: array
        items:
          $ref: '#/definitions/errorCodesAndMessage'
      supportedTransferProtocols:
        type: array
        items:
          type: string
        description: |
          Used in getExecutionResults and getAccessURL.
          Protocol names must be URL prefixes (e.g. "http", "https", "ftp", "sftp", "ftps", "scp", "webdav"). 
      supportedModules:
        type: array
        items:
          type: string
          enum: ["Processing", "Data", "Management", "Commercial",]
      defaultLimitListExecutions:
        type: integer
        format: int64
        description: The number of Executions returned by getExecutions and getStudyExecutions when limit is not specified.
      email:
        type: string
        format: utf8 # TODO: I do not know if utf8 is valid here.
      platformDescription:
        type: string
        format: utf8
      minAuthorizedExecutionTimeout:
        type: integer
        format: int64
      maxAuthorizedExecutionTimeout:
        type: integer
        format: int64
        description: 0 or absent means no max timeout. max has to be greater or equal to the min.
      defaultExecutionTimeout:
        type: integer
        format: int64
      unsupportedMethods:
        type: array
        items:
          type: string
        description: List of optional methods that are not supported by the platform.
      maxSizeDirectTransfer:
        type: integer
        format: int64
        description: |
          The maximal size of files and directories that can be transferred
          by methods Path.uploadPath and Path.downloadPath.
      defaultStudy:
        type: string
      supportedAPIVersion:
        type: string
  PipelineParameter:
    type: object
    required:
      - name
      - type
      - isOptional
      - isReturnedValue
    properties:
      name:
        type: string
      type:
        type: string
      isOptional:
        type: boolean
      isReturnedValue:
        type: boolean
      defaultValue:
        description: Default value. It can be any type.
      description:
        type: string
        format: utf8
  Pipeline:
    type: object
    required:
      - identifier
      - name
      - version
      - parameters
    properties:
      identifier:
        type: string
      name:
        type: string
        format: utf8
      version:
        type: string
      description:
        type: string
        format: utf8
      canExecute:
        type: boolean
      parameters:
        type: array
        items:
          $ref: '#/definitions/PipelineParameter'
  errorCodesAndMessage:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
  execution:
    type: object
    required:
      - pipelineIdentifier
      - status
    properties:
      name:
        type: string
        description: execution name
      pipelineIdentifier:
        type: string
        description: which pipeline that started this execution
      status:
        type: string
        "enum": ["initializing",
          "ready",
          "running",
          "finished",
          "initialization_failed",
          "execution_failed",
          "unknown",
          "killed"]
  newExecution:
    type: object
    required:
      - name
      - pipelineIdentifier
      - inputValues
    properties:
      name:
        type: string
        description: name to display to users
      pipelineIdentifier:
        type: string
      timeout:
        type: integer
        description: timeout in seconds
      inputValues:
        type: array
        items:
          $ref: '#/definitions/keyValuePair'
  executionId:
    type: string
  executionIds:
    type: array
    items:
      type: string
  keyValuePair:
    type: object
    required:
      - key
      - value
    properties:
      key:
        type: string
        description: the key value
      value: ## type is ignored here since it could be any type, such as integer, string, list, etc.
        description: the value associated with key
